# Generated by Django 5.1.2 on 2024-10-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
