# Generated by Django 5.1.2 on 2024-10-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='img',
            field=models.ImageField(upload_to='static/books/images'),
        ),
    ]
